name: Make environment
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.12.9' 
        
    - name: Make environment
      run: make install

    - name: Run tests
      run: make test
      
    - name: Upload artifacts
      uses: actions/upload-artifact@v4 
      with:
        name: test-plots
        path: ./artifacts/

    - name: Deploy artifacts to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./artifacts